/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import dao.ProdutoDAO;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pepes
 */
public class TelaRelatorios extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaRelatorios.class.getName());

    /**
     * Creates new form TelaRelatorio
     */
    public TelaRelatorios() {
    initComponents();
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnListasdePreco = new javax.swing.JButton();
        btnBalancoEstoque = new javax.swing.JButton();
        btnEstoquebaixo = new javax.swing.JButton();
        btnProdutosporCategoria = new javax.swing.JButton();
        btnMaiorMovimentacao = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblRelatorios = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        setName("tblRelatorios"); // NOI18N

        btnListasdePreco.setText("Listas de Preço");
        btnListasdePreco.addActionListener(this::btnListasdePrecoActionPerformed);

        btnBalancoEstoque.setText("Balanço Estoque");
        btnBalancoEstoque.addActionListener(this::btnBalancoEstoqueActionPerformed);

        btnEstoquebaixo.setText("Estoque baixo");
        btnEstoquebaixo.addActionListener(this::btnEstoquebaixoActionPerformed);

        btnProdutosporCategoria.setText("Produtos por Categoria");
        btnProdutosporCategoria.addActionListener(this::btnProdutosporCategoriaActionPerformed);

        btnMaiorMovimentacao.setText("Maior Movimentação");
        btnMaiorMovimentacao.addActionListener(this::btnMaiorMovimentacaoActionPerformed);

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(this::btnAtualizarActionPerformed);

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(this::btnLimparActionPerformed);

        tblRelatorios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tblRelatorios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnListasdePreco, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProdutosporCategoria)
                .addGap(18, 18, 18)
                .addComponent(btnMaiorMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEstoquebaixo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBalancoEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAtualizar)
                        .addGap(238, 238, 238)
                        .addComponent(btnLimpar))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListasdePreco)
                    .addComponent(btnBalancoEstoque)
                    .addComponent(btnEstoquebaixo)
                    .addComponent(btnMaiorMovimentacao)
                    .addComponent(btnProdutosporCategoria))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar)
                    .addComponent(btnAtualizar))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListasdePrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListasdePrecoActionPerformed
ProdutoDAO dao = new ProdutoDAO();
    List<Vector<Object>> dados = dao.obterListaDePrecos();
    
    Vector<String> colunas = new Vector<>();
    colunas.add("Produto");
    colunas.add("Preço Unitário");
    colunas.add("Unidade");
    colunas.add("Categoria");
    
    DefaultTableModel modeloTabela = new DefaultTableModel((Vector<? extends Vector>) dados, colunas);
    tblRelatorios.setModel(modeloTabela);// TODO add your handling code here:
    }//GEN-LAST:event_btnListasdePrecoActionPerformed

    private void btnBalancoEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBalancoEstoqueActionPerformed
   ProdutoDAO dao = new ProdutoDAO();
    List<Vector<Object>> dados = dao.obterBalancoFisicoFinanceiro();
    
    Vector<String> colunas = new Vector<>();
    colunas.add("Produto");
    colunas.add("Qtd em Estoque");
    colunas.add("Preço Unitário");
    colunas.add("Valor Total (R$)");
    
    DefaultTableModel modeloTabela = new DefaultTableModel((Vector<? extends Vector>) dados, colunas);
    tblRelatorios.setModel(modeloTabela); // TODO add your handling code here:
    }//GEN-LAST:event_btnBalancoEstoqueActionPerformed

    private void btnProdutosporCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosporCategoriaActionPerformed
ProdutoDAO dao = new ProdutoDAO();
    List<Vector<Object>> dados = dao.obterQtdProdutosPorCategoria();
    
    Vector<String> colunas = new Vector<>();
    colunas.add("Nome da Categoria");
    colunas.add("Quantidade de Produtos");
    
    DefaultTableModel modeloTabela = new DefaultTableModel((Vector<? extends Vector>) dados, colunas);
    tblRelatorios.setModel(modeloTabela);
    }//GEN-LAST:event_btnProdutosporCategoriaActionPerformed

    private void btnMaiorMovimentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaiorMovimentacaoActionPerformed
     ProdutoDAO dao = new ProdutoDAO(); 
    List<Vector<Object>> dados = dao.obterMaioresMovimentacoes();
    
    Vector<String> colunas = new Vector<>();
    colunas.add("Operação");
    colunas.add("Produto");
    colunas.add("Quantidade Total Movimentada");
    
    DefaultTableModel modeloTabela = new DefaultTableModel((Vector<? extends Vector>) dados, colunas);
    tblRelatorios.setModel(modeloTabela);  // TODO add your handling code here:
    }//GEN-LAST:event_btnMaiorMovimentacaoActionPerformed

    private void btnEstoquebaixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstoquebaixoActionPerformed
  ProdutoDAO dao = new ProdutoDAO();
    List<Vector<Object>> dados = dao.obterProdutosAbaixoMinimo();
    
    Vector<String> colunas = new Vector<>();
    colunas.add("Produto");
    colunas.add("Qtd Mínima");
    colunas.add("Estoque Atual");
    
    DefaultTableModel modeloTabela = new DefaultTableModel((Vector<? extends Vector>) dados, colunas);
    tblRelatorios.setModel(modeloTabela);   // TODO add your handling code here:
    }//GEN-LAST:event_btnEstoquebaixoActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
    tblRelatorios.setModel(new DefaultTableModel());  // TODO add your handling code here:
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
       ProdutoDAO dao = new ProdutoDAO();
    List<Vector<Object>> dados = dao.obterListaDePrecos();
    
    Vector<String> colunas = new Vector<>();
    colunas.add("Produto");
    colunas.add("Preço Unitário");
    colunas.add("Unidade");
    colunas.add("Categoria");
    
    DefaultTableModel modeloTabela = new DefaultTableModel((Vector<? extends Vector>) dados, colunas);
    tblRelatorios.setModel(modeloTabela);// TODO add your handling code here:
    }//GEN-LAST:event_btnAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaRelatorios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnBalancoEstoque;
    private javax.swing.JButton btnEstoquebaixo;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnListasdePreco;
    private javax.swing.JButton btnMaiorMovimentacao;
    private javax.swing.JButton btnProdutosporCategoria;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblRelatorios;
    // End of variables declaration//GEN-END:variables
}
